<a href="https://colab.research.google.com/github/amithbiju/Pytorch_tutorial/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,8],[5,6]])

MATRIX

tensor([[7, 8],
        [5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([5, 6])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,4,5],[6,7,8]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

RANDOM TENSORS


In [ ]:
# create random tensor

random_tensor = torch.rand(2,3,4)

random_tensor

tensor([[[0.9379, 0.0527, 0.5479, 0.7854],
         [0.6435, 0.0155, 0.3826, 0.1218],
         [0.1661, 0.9802, 0.8779, 0.7463]],

        [[0.0470, 0.5662, 0.9673, 0.9004],
         [0.0558, 0.1603, 0.8093, 0.1262],
         [0.2699, 0.5703, 0.4290, 0.9077]]])

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224))

random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeros and ones

In [ ]:
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(10,10))
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype


torch.float32

creating a range of tensors

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten1 = torch.arange(start=1,end=100,step=5)
one_to_ten1

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [ ]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor DataTypes

In [ ]:
float_32_tensor = torch.tensor([3.6,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False
                               )
float_32_tensor

tensor([3.6000, 6.0000, 9.0000])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.5996, 6.0000, 9.0000], dtype=torch.float16)

###Printing all details

In [3]:
some_tensor = torch.rand(5,6)
some_tensor

tensor([[0.9352, 0.5228, 0.7863, 0.8853, 0.3594, 0.6873],
        [0.6359, 0.2421, 0.3116, 0.0931, 0.8924, 0.2617],
        [0.3081, 0.2874, 0.8567, 0.9752, 0.8279, 0.9751],
        [0.9742, 0.3102, 0.1435, 0.2832, 0.4818, 0.0455],
        [0.5112, 0.8148, 0.3766, 0.2680, 0.0588, 0.8469]])

In [ ]:
print(some_tensor)
print(f"DataType of the tensor is :{some_tensor.dtype}" )
print(f"Shape of tensor is :{some_tensor.shape}" )
print(f"Device tensor is on :{some_tensor.device}" )

tensor([[0.5733, 0.2136, 0.9846, 0.3096, 0.9905, 0.8364],
        [0.8971, 0.7708, 0.6833, 0.1224, 0.1882, 0.1389],
        [0.5395, 0.6586, 0.3224, 0.9650, 0.3585, 0.5979],
        [0.1961, 0.7624, 0.4503, 0.4077, 0.8565, 0.7245],
        [0.5619, 0.0928, 0.8293, 0.4556, 0.3127, 0.6991]])
DataType of the tensor is :torch.float32
Shape of tensor is :torch.Size([5, 6])
Device tensor is on :cpu


###Operations

In [4]:
some_tensor +10

tensor([[10.9352, 10.5228, 10.7863, 10.8853, 10.3594, 10.6873],
        [10.6359, 10.2421, 10.3116, 10.0931, 10.8924, 10.2617],
        [10.3081, 10.2874, 10.8567, 10.9752, 10.8279, 10.9751],
        [10.9742, 10.3102, 10.1435, 10.2832, 10.4818, 10.0455],
        [10.5112, 10.8148, 10.3766, 10.2680, 10.0588, 10.8469]])

In [ ]:
some_tensor*10

tensor([[5.7328, 2.1361, 9.8465, 3.0960, 9.9054, 8.3638],
        [8.9707, 7.7080, 6.8325, 1.2240, 1.8820, 1.3886],
        [5.3946, 6.5859, 3.2245, 9.6504, 3.5850, 5.9790],
        [1.9606, 7.6236, 4.5030, 4.0774, 8.5655, 7.2454],
        [5.6191, 0.9275, 8.2930, 4.5563, 3.1269, 6.9907]])

In [ ]:
torch.mul(some_tensor,5)

tensor([[2.8664, 1.0681, 4.9232, 1.5480, 4.9527, 4.1819],
        [4.4853, 3.8540, 3.4163, 0.6120, 0.9410, 0.6943],
        [2.6973, 3.2930, 1.6122, 4.8252, 1.7925, 2.9895],
        [0.9803, 3.8118, 2.2515, 2.0387, 4.2827, 3.6227],
        [2.8095, 0.4638, 4.1465, 2.2782, 1.5635, 3.4954]])

###Tensor Mul


In [5]:
some_tensor*some_tensor

tensor([[0.8746, 0.2733, 0.6183, 0.7838, 0.1292, 0.4723],
        [0.4044, 0.0586, 0.0971, 0.0087, 0.7963, 0.0685],
        [0.0949, 0.0826, 0.7340, 0.9511, 0.6854, 0.9508],
        [0.9491, 0.0962, 0.0206, 0.0802, 0.2321, 0.0021],
        [0.2614, 0.6639, 0.1418, 0.0718, 0.0035, 0.7173]])

In [7]:
mul_tensor = torch.rand(3,3)

In [8]:
%%time
torch.matmul(mul_tensor,mul_tensor)

CPU times: user 849 µs, sys: 996 µs, total: 1.84 ms
Wall time: 15.2 ms


tensor([[0.6162, 0.9911, 0.5360],
        [0.1980, 0.3708, 0.2981],
        [0.2292, 0.3969, 0.2897]])

### Common mul ERRORS

In [11]:
tensor_a = torch.tensor([[1,2],[3,4],[5,6]])

tensor_b = torch.tensor([[7,10],[8,11],[5,8]])

torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  21],
        [ 61,  68,  47],
        [ 95, 106,  73]])

In [10]:
tensor_b.T

tensor([[ 7,  8,  5],
        [10, 11,  8]])

### MIN MAX MEAN SUM ETC

In [12]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [14]:
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [17]:
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [19]:
torch.sum(x) , x.sum()

(tensor(450), tensor(450))